service: S3Stats

package:
  include:
    - ../src/s3stats.js
    - ../src/node_modules/**
    
# The provider are the Global parameters
provider:
  name: aws
  runtime: nodejs6.10
  stage: ${opt:stage, 'dev'}
  accountId: ${opt:accountId, '716783647419'}
  region: ${opt:region, 'eu-west-1'}
  esEndpoint: ${opt:esEndpoint, 'https://search-opstat-qe4k7okdqmzazjkuwhavu52nyi.eu-west-1.es.amazonaws.com'}
  esIndex: ${opt:esIndex, 's3stats'}
  esType: ${opt:esType, 's3stats'}
  author: ${opt:author}
  logRetentionInDays: 1
  deploymentBucket:
    name: pprod-deploy
  vpc:
    securityGroupIds:
      - sg-6aac4d10     # Commonsrv DEV03
    subnetIds:
      - subnet-62e00f2a # 1a private
      - subnet-773b1f2c # 1b private
      
      
resources:
  
  Resources:
    #Creation of the CloudWatch Log Group
    s3statsLogGroup:
      Type: AWS::Logs::LogGroup
      Properties:
        LogGroupName: s3stats
        RetentionInDays: ${self:provider.logRetentionInDays}
        
    # Creation of the role
    lambdas3statsrole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: lambda-s3stats
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action: sts:AssumeRole

        Policies:
          - PolicyName: lambda_execution_stream # Policy for Log Group
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - "*"
          - PolicyName: ec2rights # Policy for rights on EC2
            PolicyDocument:
              Version: '2012-10-17'
              Statement:          
                - Effect: Allow
                  Action:
                    - ec2:CreateNetworkInterface
                    - ec2:DescribeNetworkInterfaces
                    - ec2:DeleteNetworkInterface
                  Resource:
                    - "*"
          - PolicyName: lambdaAccess
            PolicyDocument:
              Version: "2012-10-17"
              Statement:
                - Effect: Allow
                  Action:
                    - lambda:InvokeFunction
                  Resource:
                    - "arn:aws:lambda:eu-west-1:716783647419:function:s3stats"
          - PolicyName: s3rights # Policy for rights on S3
            PolicyDocument:
              Version: '2012-10-17'
              Statement:          
                - Effect: Allow
                  Action:
                    - s3:ListAllMyBuckets
                  Resource:
                    - "*"
          - PolicyName: CWrights # Policy for rights on CloudWatch
            PolicyDocument:
              Version: '2012-10-17'
              Statement:          
                - Effect: Allow
                  Action:
                    - cloudwatch:GetMetricStatistics
                  Resource:
                    - "*"          
          - PolicyName: esgenericrights # Policy on Elasticsearch
            PolicyDocument:
              Version: '2012-10-17'
              Statement:       
                - Effect: Allow
                  Action:
                    - es:ESHttpGet
                    - es:ListDomainNames
                    - es:ESHttpPost
                    - es:ESHttpPut
                  Resource:
                    - "*"
          - PolicyName: esaccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:                 
                - Effect: Allow
                  Action:
                    - es:*
                  Resource:
                    - arn:aws:es:${self:provider.region}:${self:provider.accountId}:domain/opstat
    
    EventRule: 
      Type: "AWS::Events::Rule"
      Properties: 
        Name: "s3stats"
        Description: "Rule for Loging s3 volume by storage type in ES"
        ScheduleExpression: "cron(02,17,32,47 * ? * * *)"
        State: "ENABLED"
        Targets: 
          - 
            Arn: arn:aws:lambda:eu-west-1:716783647419:function:s3stats
            Id: "lambda-s3stats"
          
    PermissionForEventsToInvokeLambda: 
      Type: "AWS::Lambda::Permission"
      Properties: 
        FunctionName: s3stats
        Action: "lambda:InvokeFunction"
        Principal: "events.amazonaws.com"
        SourceArn: 
          Fn::GetAtt: 
            - "EventRule"
            - "Arn"      
    
functions:
    s3stats:
      name: s3stats
      description: Log volume size by storageytpe in ES
      timeout: 120
      handler: src/s3stats.handler
      tags:
        project: FinOps
        ITOwner: ${self:provider.author}
      environment:
        elasticsearch_endpoint: ${self:provider.esEndpoint}
        elasticsearch_index: ${self:provider.esIndex}
        elasticsearch_type: ${self:provider.esType}