AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FinOps serverless application.

Resources:

  test:
    Type: AWS::Serverless::Function
    Properties:
      Handler: ec2running.handler
      Runtime: nodejs6.10
      Timeout: 240
      Environment:
        Variables:
          elasticsearch_endpoint: "https://search-opstat-qe4k7okdqmzazjkuwhavu52nyi.eu-west-1.es.amazonaws.com"
          elasticsearch_index: "ec2running"
          elasticsearch_type: "ec2running"
          STAGE: "DEV"
