AWSTemplateFormatVersion : '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: FinOps serverless application.

Resources:

  test:
    Type: AWS::Serverless::Function
    Properties:
      Handler: s3stats.handler
      Runtime: nodejs6.10
      Timeout: 30
      Environment:
        Variables:
          elasticsearch_endpoint: "https://search-opstat-qe4k7okdqmzazjkuwhavu52nyi.eu-west-1.es.amazonaws.comlocaltable"
          elasticsearch_index: "s3stats"
          elasticsearch_type: "s3stats"
          STAGE: "DEV"